# Generated by Django 5.2.6 on 2026-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truefalse',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('FB', 'Fill in the Blank'), ('READ', 'Reading Passage')], default='MCQ', max_length=10),
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='TrueFalse',
        ),
    ]
